language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - npm prune
after_success:
  - bash ./deploy/publish_to_npm.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
